edit yml file

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -40,8 +40,13 @@ jobs:
           HOST: ${{ secrets.HOST }}
           USER: ${{ secrets.USER }}
         run: |
-          # Debug: Check the value of HOST
-          echo "HOST is: $HOST"
+          # Debug: Check if HOST secret is set properly
+          if [ -z "$HOST" ]; then
+            echo "Error: HOST is not set"
+            exit 1
+          else
+            echo "HOST is set to $HOST"
+          fi
 
           # Create the .ssh directory if it doesn't exist
           mkdir -p ~/.ssh
@@ -49,9 +54,6 @@ jobs:
           # Save the private key
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/key.pem
           chmod 600 ~/.ssh/key.pem
-
-          # Debug: Check SSH key permissions
-          ls -l ~/.ssh
 
           # Add the server to known hosts
           ssh-keyscan $HOST >> ~/.ssh/known_hosts
